"""
Django settings for search project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ---- Local vs server ----
# Apne computer par kuch set karne ki zarurat nahi (neeche ke defaults local ke liye hain).
# Server par daalna ho toh ye environment variables set karo:
#   DJANGO_DEBUG=0
#   DJANGO_SECRET_KEY=<lamba random secret>
#   DJANGO_ALLOWED_HOSTS=example.com,www.example.com
#   DJANGO_CSRF_TRUSTED_ORIGINS=https://example.com      (https ke peeche ho toh)
def _env_bool(name, default):
    value = os.environ.get(name)
    return default if value is None else value.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


_INSECURE_DEV_KEY = 'django-insecure-9cfi4a=7i8xv0x)^nh8_ycjhse7hmt4n6q!n*-dugzjdfhtx3$'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _INSECURE_DEV_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

if not DEBUG:
    if SECRET_KEY == _INSECURE_DEV_KEY:
        raise ImproperlyConfigured('DJANGO_DEBUG=0 ke saath DJANGO_SECRET_KEY set karna zaruri hai.')
    # Sirf https par cookies bhejo (http par chalana ho toh DJANGO_SECURE_COOKIES=0)
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = _env_bool('DJANGO_SECURE_COOKIES', True)
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fileindex',  # Hamara custom app
    'licensing',  # License: key, expiry, block
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'licensing.middleware.LicenseMiddleware',   # license khatam ho toh pages band (LICENSE_ENFORCED ho tabhi)
]

ROOT_URLCONF = 'search.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'search.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # server par: python manage.py collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SCAN_LOCATIONS = {
    'c': {'label': 'C: Drive', 'path': 'C:\\'},
    'd': {'label': 'D: Drive', 'path': 'D:\\'},
}

SCAN_MIN_DIGITS = 5

# Aakhri scan itne din se purana ho toh Bulk Search page par "dobara scan karo" ki chetavni dikhti hai
SCAN_STALE_DAYS = 7

SCAN_SKIP_DIRS = (
    '$Recycle.Bin', 'System Volume Information', 'Windows', 'Program Files',
    'Program Files (x86)', 'ProgramData', 'AppData', 'node_modules', '.git',
    '__pycache__', 'venv', '.venv',
)

SCAN_WORKERS = 2 


# ---- License (customer ke PC par) ----
# Installer banate waqt `licensing/build_config.py` ban jati hai (installer/make_build_config.py): usme ENFORCED=True,
# server ka address aur PUBLIC key hoti hai, aur wo .exe ke andar band ho jati hai. Customer use badal nahi sakta.
# Apne computer par (build_config nahi) license check band rehta hai, jab tak environment variable na do:
#   EXCEL_FINDER_LICENSE_ENFORCED=1  EXCEL_FINDER_LICENSE_SERVER=http://127.0.0.1:8800  EXCEL_FINDER_LICENSE_PUBLIC_KEY=...
try:
    from licensing import build_config as _license_build
except ImportError:
    _license_build = None

if _license_build is not None:
    LICENSE_ENFORCED = bool(getattr(_license_build, "ENFORCED", True))
    LICENSE_SERVER_URL = getattr(_license_build, "SERVER_URL", "")
    LICENSE_PUBLIC_KEY = getattr(_license_build, "PUBLIC_KEY", "")
    LICENSE_BUY_URL = getattr(_license_build, "BUY_URL", "")
    LICENSE_SUPPORT = getattr(_license_build, "SUPPORT", "")
else:
    LICENSE_ENFORCED = _env_bool("EXCEL_FINDER_LICENSE_ENFORCED", False)
    LICENSE_SERVER_URL = os.environ.get("EXCEL_FINDER_LICENSE_SERVER", "")
    LICENSE_PUBLIC_KEY = os.environ.get("EXCEL_FINDER_LICENSE_PUBLIC_KEY", "")
    LICENSE_BUY_URL = os.environ.get("EXCEL_FINDER_LICENSE_BUY_URL", "")
    LICENSE_SUPPORT = os.environ.get("EXCEL_FINDER_LICENSE_SUPPORT", "")
LICENSE_CHECK_INTERVAL_HOURS = 24   # app online ho toh itne ghante me ek baar server se check
LICENSE_WARN_DAYS = 14              # expiry se itne din pehle chetavni
