# Generated by Django 6.1.1 on 2026-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenseState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.CharField(blank=True, max_length=40)),
                ("token", models.TextField(blank=True)),
                ("blocked_code", models.CharField(blank=True, max_length=20)),
                ("blocked_message", models.CharField(blank=True, max_length=300)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_ok", models.BooleanField(default=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("max_seen_time", models.DateTimeField(blank=True, null=True)),
                ("trial_started", models.BooleanField(default=False)),
                ("searches_total", models.PositiveIntegerField(default=0)),
                ("scans_total", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "License",
            },
        ),
    ]
