# Generated by Django 6.1.1 on 2026-10-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensestate",
            name="account_email",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="licensestate",
            name="device_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
