# Generated by Django 6.1.1 on 2026-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_account_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licensestate",
            name="device_token",
        ),
        migrations.RemoveField(
            model_name="licensestate",
            name="trial_started",
        ),
        migrations.AddField(
            model_name="licensestate",
            name="account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
