# Generated by Django 6.1.1 on 2026-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('extracted_data', models.TextField(help_text='All extracted text/numbers from the file')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
