# Generated by Django 6.1.1 on 2026-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0002_scantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='files_indexed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='folders_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
