# Generated by Django 6.1.1 on 2026-09-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0003_scantask_files_indexed_scantask_folders_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileindex',
            name='extracted_data',
        ),
        migrations.AddField(
            model_name='fileindex',
            name='file_mtime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fileindex',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='files_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='files_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='NumberIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('sheet', models.CharField(blank=True, max_length=100)),
                ('row', models.PositiveIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='fileindex.fileindex')),
            ],
        ),
    ]
