# Generated by Django 6.1.1 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0004_remove_fileindex_extracted_data_fileindex_file_mtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileindex',
            name='index_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='numberindex',
            name='col',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
