# Generated by Django 6.1.1 on 2026-09-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0005_fileindex_index_version_numberindex_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Number Search',
                'verbose_name_plural': 'Bulk Number Search',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fileindex.fileindex',),
        ),
    ]
