# Generated by Django 6.1.1 on 2026-10-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0007_numberindex_match_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1000)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="fileindex.scantask",
                    ),
                ),
            ],
        ),
    ]
