# Generated by Django 6.1.1 on 2026-10-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0008_scanfailure"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BulkSearch",
        ),
    ]
