# Generated by Django 6.1.1 on 2026-10-09 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "key_hint",
                    models.CharField(
                        editable=False,
                        help_text="Key ke aakhri akshar, pehchaan ke liye",
                        max_length=16,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("yearly", "Yearly"),
                            ("lifetime", "Lifetime"),
                            ("trial", "Free trial"),
                        ],
                        default="yearly",
                        max_length=10,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                (
                    "max_machines",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Kitne PC par chal sakta hai"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pehli activation se kitne din. Yearly: 365 (khali chhodo toh apne aap). Lifetime: khali.",
                        null=True,
                    ),
                ),
                (
                    "offline_grace_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="Server se bina check kiye app itne din chalega",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "first_activated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Khali = kabhi expire nahi (lifetime) ya abhi activate nahi hua",
                        null=True,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Tick karte hi app ka license band ho jata hai (agle check par)",
                    ),
                ),
                ("revoked_reason", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=64)),
                ("machine_name", models.CharField(blank=True, max_length=200)),
                ("app_version", models.CharField(blank=True, max_length=40)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Band karne par ye PC license se hat jata hai (seat khali)",
                    ),
                ),
                ("searches_total", models.PositiveIntegerField(default=0)),
                ("scans_total", models.PositiveIntegerField(default=0)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="license_server.license",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "unique_together": {("license", "machine_id")},
            },
        ),
    ]
