# Generated by Django 6.1.1 on 2026-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Jaise 1.1.0 (app ke search/version.py jaisa)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        help_text="Setup.exe ka https link (Google Drive ka 'Anyone with the link' share link chalega)",
                        max_length=500,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="Setup.exe ka SHA-256 (build ke ant me dikhta hai). Ye bhara ho tabhi app me ek-click 'Update now' chalta hai; khali ho toh sirf 'Download' link dikhta hai.",
                        max_length=64,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Naya kya hai: ek line me ek baat"
                    ),
                ),
                (
                    "min_version",
                    models.CharField(
                        blank=True,
                        help_text="Isse purane version par update zaruri (laal banner). Khali = zaruri nahi",
                        max_length=20,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick karne par customers ko nahi dikhta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts (customers)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("license_server.license",),
        ),
        migrations.AddField(
            model_name="activation",
            name="secret_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Account login par is PC ko mila secret (hash)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="password_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Sirf account (email + password) wale customers ke liye",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (no access yet)"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("lifetime", "Lifetime"),
                    ("trial", "Free trial"),
                ],
                default="yearly",
                max_length=10,
            ),
        ),
    ]
