# Generated by Django 6.1.1 on 2026-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_server", "0002_accounts_and_releases"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.RemoveField(
            model_name="activation",
            name="secret_hash",
        ),
        migrations.RemoveField(
            model_name="license",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="activation",
            name="files_indexed",
            field=models.PositiveIntegerField(
                default=0, help_text="Is PC ke index me abhi kitni Excel files hain"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="reset_code_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Password reset code ka hash (ek baar chalta hai)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="reset_expires",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for key"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("lifetime", "Lifetime"),
                ],
                default="yearly",
                max_length=10,
            ),
        ),
    ]
